### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by gzhynko** [lhark/truckersmp-cli#112]
Is Discord RPC supported? I can't seem to get it to display rich presence data on my native Discord installation. I'm running `Ubuntu 20.04`.
Any help would be appreciated.

**Comment by Lucki** [comment]
I don't recall ETS2, ATS or TruckersMP using rich presence, did I miss something?
We're neither currently supporting it nor are we actively denying it.

A quick search revealed a bunch of third party stuff which all seem to require the scs sdk.

**Comment by gzhynko** [comment]
Thanks for the answer! Rich presence can be enabled through TruckersMP’s options, though when running it with Proton, nothing gets displayed in Discord

**Comment by Lucki** [comment]
Discords activities (former rich presence) seem to be included at compile time which is then bound to the OS.
* If there were a `discord-rpc.dll` somewhere it would probably possible to replace that with something like [this](https://github.com/Marc3842h/rpc-wine) but it seems TruckersMP has compiled it inside their mod dll.
* Which leads to our best bet by trying https://github.com/0e4ef622/wine-discord-ipc-bridge which is "bridging the gap between Windows named pipes) and Unix domain sockets".
* It should also work by running Discord in wine inside the same prefix.

If that works we should discuss if that's something we should include.

**Comment by gzhynko** [comment]
I’m not sure how to make wine-discord-ipc-bridge work with truckersmp-cli, but I guess it would work if set up properly. Installing Discord in wine didn’t work for me - it fails with many errors.

**Comment by Lucki** [comment]
The wine discord ipc bridge is working, tested with proton.

![grafik](https://user-images.githubusercontent.com/1408843/96008855-4730ac00-0e40-11eb-921e-95d75b6e9e50.png)

I guess that's something we could easily include, it just needs a startup in the same wineprefix beforehand.

Related questions:
* Ship it with tuckersmp-cli? (need to figure out how to handle such subprojects)
* Optionally depend on it? (name is quite bad and currently no packages, also it's an exe which probably isn't in any `$PATH`)
* The bridge is in 32bit and throws some errors when trying to build as 64bit. It worked as 32bit though.

@kakurasan Any opinions?

**Comment by kakurasan** [comment]
If we only need the [wine-discord-ipc-bridge](https://github.com/0e4ef622/wine-discord-ipc-bridge), we can automate:

* Downloading `winediscordipcbridge.exe`(`https://raw.githubusercontent.com/0e4ef622/wine-discord-ipc-bridge/4ce68383a536b4e44b71a6764dba5ba3e2ea0aa1/winediscordipcbridge.exe`) to `$XDG_DATA_HOME/truckersmp-cli/wine-discord-ipc-bridge/`
* Running `$XDG_DATA_HOME/truckersmp-cli/wine-discord-ipc-bridge/winediscordipcbridge.exe` (and waiting 10 seconds) before starting ETS2MP/ATSMP

and add an option for it (e.g. `--use-wine-discord-ipc-bridge`).

Regarding Proton, we need to respect `PROTON_NO_ESYNC` environment variable (set `WINEESYNC` value) to avoid the following errors:

* `err:esync:esync_init Server is running with WINEESYNC but this process is not, please enable WINEESYNC or restart wineserver.`
* `err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.`

**Comment by Lucki** [comment]
>     * and waiting 10 seconds

I think the 10 seconds aren't needed. Looking in their issues it's already mentioned. I don't think we have to add any waiting because TruckersMP takes pretty long to startup already.

> add an option for it

I probably would turn it on by default because it's a feature of the original and it can be turned off inside the mod menu already.

> we need to respect `PROTON_NO_ESYNC` environment variable (set `WINEESYNC` value) to avoid the following errors:

I haven't run into this issue. Can you be more precise where we're running into this?
I've just started the bridge with proton and then truckersmp-cli with proton.

**Comment by kakurasan** [comment]
> I haven't run into this issue. Can you be more precise where we're running into this?

If the user uses Proton version of `wine` command (`/path/to/Proton X.Y/dist/bin/wine`) directly, `WINEESYNC` can not be changed when running multiple programs with the same wineprefix.

```
$ WINEESYNC=1 /path/to/Proton\ 5.0/dist/bin/wine notepad &
$ WINEESYNC=0 /path/to/Proton\ 5.0/dist/bin/wine regedit &
00cc:err:esync:esync_init Server is running with WINEESYNC but this process is not, please enable WINEESYNC or restart wineserver.

$ WINEESYNC=0 /path/to/Proton\ 5.0/dist/bin/wine notepad &
$ WINEESYNC=1 /path/to/Proton\ 5.0/dist/bin/wine regedit &
00a8:err:esync:esync_init Failed to open esync shared memory file; make sure no stale wineserver instances are running without WINEESYNC.
```

I guess @Lucki ran `/path/to/proton run /path/to/winediscordipcbridge.exe`. This also is OK because the `proton` script respects `PROTON_NO_ESYNC`.

> I think the 10 seconds aren't needed. Looking in their issues it's already mentioned. I don't think we have to add any waiting because TruckersMP takes pretty long to startup already.

> I probably would turn it on by default because it's a feature of the original and it can be turned off inside the mod menu already.

Makes sense.

>  The problem is with updates on their side. That's another update mechanism we'd need to implement.

Currently I think that it doesn't need updating because:

* The current binary is "working" as expected
* The URL is permanent and we don't need to update MD5 for `download_files()` even if they update the binary

**Comment by gzhynko** [comment]
I've just tested @kakurasan's `winediscordipcbridge` branch and it works flawlessly well with proton!

**Comment by kakurasan** [comment]
>> The problem is with updates on their side. That's another update mechanism we'd need to implement.

> Currently I think that it doesn't need updating because ...

When we really need the "updated" binary, we only need to replace the old permanent URL and its MD5 with the new permanent URL and its MD5 (and release a [new version](https://github.com/lhark/truckersmp-cli/releases) for it). Then users would download the new file because of MD5 mismatch.

@gzhynko Thanks for testing!
