### ISSUE TITLE
Failed to get Wine process list

### ISSUE THREAD

**Issue by ACheshirov** [lhark/truckersmp-cli#117]
When I run this command "truckersmp-cli -n mysteamaccname --ets2 --update" in order to automatically install everything I need.
I get that "Failed to get Wine process list:".

I have installed Wine. Its version is 5.0.1

**Comment by Lucki** [comment]
Thanks for your bug report! Since the default is proton I'm not sure why you're running into the wine area in the first place.

Unfortunately you ignored our precious issue template when creating this bug so I have to ask for additional information again. You can find the latest issue template here: https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Lucki** [comment]
@kakurasan The bug is that we're trying to check the steam process in a prefix which isn't created yet.

On an initial run `Args.prefixdir` is set but still empty until we're trying to start the game the first time which will set up the prefix environment.
https://github.com/lhark/truckersmp-cli/blob/0e7887f0720b8cb269d60c282b0969f33f46ee3d/truckersmp_cli/steamcmd.py#L50
https://github.com/lhark/truckersmp-cli/blob/0e7887f0720b8cb269d60c282b0969f33f46ee3d/truckersmp_cli/steamcmd.py#L123

Interesting that `winedbg` won't set up a non-exisiting prefix for us…
https://github.com/lhark/truckersmp-cli/blob/0e7887f0720b8cb269d60c282b0969f33f46ee3d/truckersmp_cli/utils.py#L136

Some brainstorming how we could solve this:
* Call [`wineboot --init`](https://manpages.ubuntu.com/manpages/bionic/man1/wineboot-stable.1.html) to make sure the prefix is initialized. IMHO this seems like the correct way but will change the whole prefix every time we switch between a wine and a proton call. We should make sure when using proton that the wine version from proton is used so there won't be any prefix up- and downgrading when changing executables.
* Test if the folder or some crucial files exist beforehand. Probably the more easier way. We still have to tackle that wine-switching as it seems to already be the case.

**Comment by kakurasan** [comment]
> Interesting that `winedbg` won't set up a non-exisiting prefix for us…
> https://github.com/lhark/truckersmp-cli/blob/0e7887f0720b8cb269d60c282b0969f33f46ee3d/truckersmp_cli/utils.py#L136

When the top-level directory [(Defaults)](https://github.com/lhark/truckersmp-cli/blob/master/README.md#wineprefix) exists, it sets up the prefix properly: We only need to call `os.makedirs("/path/to/prefix", exist_ok=True)` before running `winedbg`.
