### ISSUE TITLE
problem running exe

### ISSUE THREAD

**Issue by david-alan-oneill** [lhark/truckersmp-cli#14]
All files are now downloading after patch but getting this error now. Is it something i am doing wrong?

Press enter if you are good to go:
./truckersmp-cli: 58: read: arg count
wine: Bad EXE format for Z:\home\david\.wine\truckersmp-cli\truckersmp-cli.exe.

**Comment by lhark** [comment]
The "Bad EXE" message from wine usually means the target architecture of the wine prefix doesn't match that of the executable. Is your wine prefix (~/.wine) setup in 32bits or 64bits ? Because the mod will only run in with 64bits wine prefix.

Could you provide the command the command you used to launch the script and the full output ?

**Comment by david-alan-oneill** [comment]
It was a 32 bit installation, thanks.
