### ISSUE TITLE
Don't work yellow cursor in Tab menu

### ISSUE THREAD

**Issue by RockBomber** [lhark/truckersmp-cli#3]
Thank You for this launcher!
Pretty works on Kubuntu 17.04 (KDE Plasma 5.9.4).
But don't work yellow cursor in Tab menu.
When I often click left button, I can see flickering yellow cursor, but can't make for it work.
I run truckersmp with wine-1.8.7 and with wine-2.4 (Staging).
Graphics: Geforce GTX 860M with proprietary drivers Nvidia 375.
Anybody have this problem?﻿

**Comment by lhark** [comment]
I'm not sure i understand your problem. Are you trying to launch `truckersmp-cli` from your file browser or some kind of quicklaunch menu ? (i don't use KDE)
I think the problem is that you don't provide the required arguments to the script. If you run `./truckersmp-cli` in your terminal, you'll see that you need to provide the path to the ETS2 install folder.

**Comment by RockBomber** [comment]
Sorry for my bad English)
I don't have problem with running of launcher. Game run, and I can play.
But when I open in game "TAB" menu (which contains players list and setting button), I can not control yellow cursor for interact with this "TAB" menu.

**Comment by lhark** [comment]
Oh... I completly misunderstood you. I actually have the same problem, and i don't know how to fix it. I would look for a solution on the ets2mp developers side, but seeing as they are pretty much hostile to anything linux related, i don't have much hope :(
