### ISSUE TITLE
Problem with -x argument

### ISSUE THREAD

**Issue by quimbydogg** [lhark/truckersmp-cli#37]
I haven't used truckersmp-cli in awhile.  Recently updated to the newest version and having an issue executing now.

Running the command: `./truckersmp-cli -asw -x "/mnt/drive4/prefixes/ATS/"` based on the samples in readme but this generates an error that the game is not found in the local user /share/truckersmp-cli path.  It seems that the path I specify with the -x argument is not actually searched?  Not sure if this is a bug or just me doing something stupid.

Thanks for any help.

**Comment by Lucki** [comment]
I'm not sure what's the problem here. Please also run the command with `-v` and paste the output here.

A few possible errors from your vague description:

1. **Maybe you're confused what a prefix is**

    The prefix represents the windows installation and points to the root (drive_c).
You can install software into that prefix or tell applications from other directories to use that environment. The game files _can_ lie in a prefix but they don't have to. Either way you have to provide the path (`-g`) if the game files aren't in the default path.

    Since you've chosen to use wine instead of proton you also have to install steam into the same prefix and start it before you start truckersmp.

2. > the game is not found in the local user /share/truckersmp-cli path

    Since you're not providing a path for the game data files (`-g`) it's expected to find the files at `$XDG_DATA_HOME/truckersmp-cli/American Truck Simulator/data/`.
If you want to download them to the default or any other folder also use `-u` in the command.

**Comment by quimbydogg** [comment]
Thanks for the quick reply, I appreciate it.  I didn't realize -g needed to be used (I guess I thought the folder would be picked up automatically from the steam default in the prefix).  Adding the pathing with the -g flag fixed everything.  Thanks again!
