### ISSUE TITLE
Force Feedback plugin not working

### ISSUE THREAD

**Issue by JeroenDonners** [lhark/truckersmp-cli#44]
For ETS2/Proton, I cannot get force feedback working for a Logitech G25 steering wheel. Using the [FFB plugin](https://forum.scssoft.com/viewtopic.php?t=249622) I can get it working in regular Linux Steam (singleplayer), but not in truckersmp-cli. I've tried both the Linux plugin (mentioned above) and the [Windows plugin](https://forum.scssoft.com/viewtopic.php?t=49772). I've tried adding the plugin's files to the installation directory, but that did not work. Is this a known issue with truckersmp-cli, or are there some other steps to get it working?

**Comment by squadramunter** [comment]
Did you look into this directory? ~/.local/share/truckersmp-cli/Euro\ Truck\ Simulator\ 2/data/bin/

**Comment by JeroenDonners** [comment]
Yes, I placed both the Linux and Windows versions of the plugin in "win_x64/plugins/" and in "win_x86/plugins/" under the directory you mentioned. This should correspond to the default steam directory where the force feedback plugin is working: "~/.steam/steam/steamapps/common/Euro\ Truck\ Simulator\ 2/bin/linux_x64/plugins/".

**Comment by Lucki** [comment]
First make sure that it should work online because most mods are disabled there. Since this uses the windows version you'll need the windows plugin. Make sure you've installed everything that's mentioned as a requirement. If it's still not working look that you can somehow know if the game has picked up the plugin. If yes: There's most likely something going wrong in the communication of wine to the steering wheel.

Either what it is, there's nothing we can do about since every part I've mentioned above is handled by someone other.

**Comment by leillo1975** [comment]
If you use new-lg4ff, you don't need plugins. This is a new module driver that enables a lot of effects on Logitech Drivers:
Take a look:
https://github.com/berarma/new-lg4ff
This driver enables FFB on ETS/ATS without plugins in native and Wine mode. The rest of car games gain FFB also (rFactor 1&2, RACE 07, Automobilista 1&2 ... )

**Comment by Lucki** [comment]
The driver mentioned above seems much more viable than a single plugin for one game so I'm closing this.
