### ISSUE TITLE
Music doesnt work on TruckersMP

### ISSUE THREAD

**Issue by Klairm** [lhark/truckersmp-cli#48]
On TruckersMP the custom music placed on the folder doesn't work, it doesn't get detected by the game, but if I play the game ETS2 without TruckersMP it will work, anyway to fix this?

**Comment by Christopher-S-25** [comment]
You have to place the music files on the music folder of the prefix that truckersmp-cli uses and when you find it, the ets2 folder is usually placed at "pfx/drive_c/users/[user]/My Documents/Euro Truck Simulator 2/music"
where [user] is one of the users on the prefix that contain Euro Truck Simulator 2 folder on My Documents. If you use steam proton for example, its going to be steamuser.

**Comment by Klairm** [comment]
I use the native version of ETS2 , so I think it doesn't have a pfx , I searched on the prefix directories of proton games but i didn't found it

**Comment by Christopher-S-25** [comment]
truckersmp-cli uses proton or wine to work with truckersmp. You might be using the native version while playing offline, but when playing truckersmp it uses a proton or a wine pfx, depending on what options you use with truckersmp-cli, because the truckersmp mod does not have a Linux native port. That means the folders used by native ETS2 are not used by the truckersmp-cli ETS2 .If you run on default settings, the prefix should be located inside the truckersmp-cli folder: truckersmp-cli/Euro Truck Simulator 2/prefix

**Comment by Klairm** [comment]
Thanks a lot! It worked 

Happy xmas
