### ISSUE TITLE
Can start launcher

### ISSUE THREAD

**Issue by Crossik9** [lhark/truckersmp-cli#5]
CreateProcess("\bin\win_x64\eurotrucks2.exe -nointro -64bit") failed; error code = 0x00000002

**Comment by lhark** [comment]
Hello,

Seeing as you provided only so little information, I can only try to guess what your problem is.
The error code you encountered basicaly means: "File not found".

My hypothesis is that you tried to run the script ./truckersmp-cli without any argument.
As stated in the README https://github.com/lhark/truckersmp-cli#usage , you also need to provide the path to your ETS2 install folder. I pushed a new version that now checksfor this argument.

**Comment by Crossik9** [comment]
Hi, thanks for answer. I am using Ubuntu 17, play wiht linux with 64 prefix.
I dont know much about wine, i manage to run the launcher one time with commands winarch and winprefix but then i restart pc and cant find the command anymore.

**Comment by lhark** [comment]
If you are using a standard wine installation, the command should look something like that : 
 truckersmp-cli ~/.wine/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/Euro\ Truck\ Simulator\ 2
If your wineprefix is different, be sure to prefix your command with WINEPREFIX=<whatever> , WINARCH is already defined in the script.
