### ISSUE TITLE
Doesn't Open in Debian 10

### ISSUE THREAD

**Issue by Dekar13** [lhark/truckersmp-cli#56]
Doesn't open in Debian 10.
When I run the truckersmp-cli, the installation process starts, but only some of it is loading.
Why is this problem?
![git1](https://user-images.githubusercontent.com/62595520/77415391-7b287f00-6dd3-11ea-9548-5c3124aaca2c.png)
![git2](https://user-images.githubusercontent.com/62595520/77415396-7e236f80-6dd3-11ea-92ce-af6e069d6d04.png)
![git3](https://user-images.githubusercontent.com/62595520/77415401-7fed3300-6dd3-11ea-951e-0bb58b1d9e2e.png)

**Comment by Lucki** [comment]
If you haven't already test #31 first.

If the problem still persists please add the `-v` switch for more in-depth messages.
When reporting back post your output as [code](https://guides.github.com/features/mastering-markdown/) probably behind a [spoiler](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287) since it will get long and make sure there aren't any overlapping lines by widening your terminal before or by redirecting the output into a file by appending `> /path/to/file.log`.

**Comment by Dekar13** [comment]
Sorry, number 31 didn't work either.

`/home/enes/.cache/truckersmp-cli
checking for errors
Using 227300
gamedir: /home/enes/.steam/debian-installation/steamapps/common/Euro Truck Simulator 2/
prefixdir: /home/enes/.steam/debian-installation/steamapps/compatdata/227300/
protondir: /home/enes/.steam/debian-installation/steamapps/common/Proton 5.0/
updating mod files
fatal: not a git repository (or any of the parent directories): .git
better do not self update
--2020-03-25 22:50:22--  https://update.ets2mp.com/files.json
update.ets2mp.com (update.ets2mp.com) çözümleniyor... 104.27.137.183, 104.27.136.183, 2606:4700:3032::681b:88b7, ...
update.ets2mp.com (update.ets2mp.com)[104.27.137.183]:443 bağlanılıyor... bağlantı kuruldu.
HTTP isteği gönderildi, yanıt bekleniyor... 200 OK
Uzunluk: 9138 (8,9K) [application/json]
Kayıt yeri: `/tmp/truckersmp-cli.DflxD4PkFG'

          /tmp/truc   0%[                    ]       0  --.-KB/s               Segmentation fault
removing /tmp/truckersmp-cli.DflxD4PkFG and /tmp/truckersmp-cli.c4OrRkt8BX`

**Comment by Dekar13** [comment]
Thank you very much, it worked.
