### ISSUE TITLE
Not A Git Repository?

### ISSUE THREAD

**Issue by wolfofodin1986** [lhark/truckersmp-cli#72]
I keep getting this error - fatal: not a git repository (or any of the parent directories): .git

I can't start it up because of this, halp.

**Comment by wolfofodin1986** [comment]
I tried git init but now I get fatal: no such branch: 'master'

**Comment by Lucki** [comment]
Hm, that shouldn't be blocking anything…

Things you can try:
* Clone this repository instead of downloading the source zip file

Things you have to do if you want further help:
* Run your command again and append `-vv`
* Post the command you're executing
* Post the complete terminal log file

When posting keep in mind that GitHub supports various editing features - use them!
